version: "3"
services:

  nifi_monitor:
    build:
      context: .
    container_name: nifi_monitor
    image: nifi_monitor
    ports:
      - "9092:5000"
      - "3000"
    environment:
     - BASE_URL=http://localhost:3000    #https://<Nifi Domain>:<Port>
